variables:
  majorVersion: '4.8.0'
  minorVersion: $[counter('minorVersion', 1)]

stages:
  - stage: Setup
    displayName: Setup
    jobs:
    - job:
      displayName: Build Variables
      pool:
        vmImage: 'ubuntu-20.04'
      steps:
        # Set the build name properly.  The 'name' property won't recursively expand so hack here:
        - bash: |
            NUGETVERSION="${MAJORVERSION}-${MINORVERSION}"
            echo "##vso[build.updatebuildnumber]$NUGETVERSION"
          displayName: Set Build Name
  - stage: Build
    jobs:
    - job: Build
      pool:
        vmImage: ubuntu-20.04
      steps:
        - bash: |
            NUGETVERSION="${MAJORVERSION}-${MINORVERSION}"
            echo $NUGETVERSION
            sed -i'' -e "s/<PackageVersion>[0-9.*]\+<\/PackageVersion>/<PackageVersion>${NUGETVERSION}<\/PackageVersion>/g" FFMpegCore/FFMpegCore.csproj
          displayName: Update Version
        - task: DotNetCoreCLI@2
          displayName: Build
          inputs:
            command: 'build'
            projects: 'FFMpegCore.sln'
            arguments: '/p:Configuration=Release'

        - publish: FFMpegCore/bin/Release
          artifact: 'nupkg'
        - task: DotNetCoreCLI@2
          inputs:
            command: 'push'
            packagesToPush: 'FFMpegCore/bin/Release/*.nupkg'
            nuGetFeedType: 'internal'
            publishVstsFeed: '7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/783c2dce-dbc3-4218-8816-4a5e12af4d84'
